name: Pull Request to main
run-name: ""
"on":
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled
    branches:
      - main
jobs:
  analyze:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: setup-go
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - id: app-token
        name: Authenticate Read-Only App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TWINSCAN_READ_ONLY_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.TWINSCAN_READ_ONLY_APP_PRIVATE_KEY }}
      - id: cross-registry-access
        name: Configure cross registry access
        run: git config --global url."https://x-oauth-basic:$MASTER_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          MASTER_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: install-dep
        name: Install dependencies
        run: go mod download
      - id: go-generate
        name: Run generate
        run: go generate ./...
      - id: go-analysis-config
        name: Configure Static Analysis
        run: |2
          cat <<-EOF > .golangci.yml
          version: "2"
          linters:
            exclusions:
              presets:
                - comments
                - common-false-positives
                - legacy
                - std-error-handling
              paths:
                - third_party$
                - builtin$
                - examples$
          formatters:
            exclusions:
              paths:
                - third_party$
                - builtin$
                - examples$
          EOF
      - id: go-analysis
        name: Static Analysis
        uses: golangci/golangci-lint-action@v8
        with:
          args: --verbose --timeout=15m
          version: latest
    strategy:
      matrix:
        go-version:
          - stable
    needs:
      - initialize
    permissions:
      checks: write
      contents: read
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: setup-go
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - id: app-token
        name: Authenticate Read-Only App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TWINSCAN_READ_ONLY_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.TWINSCAN_READ_ONLY_APP_PRIVATE_KEY }}
      - id: cross-registry-access
        name: Configure cross registry access
        run: git config --global url."https://x-oauth-basic:$MASTER_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          MASTER_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: install-dep
        name: Install dependencies
        run: go mod download
      - id: go-generate
        name: Run generate
        run: go generate ./...
      - id: go-build
        name: Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.go-os }} GOARCH=${{ matrix.go-arch }} go build $BUILD_FLAGS -v -o ./dist/sandbox-svc-review cmd/main.go
        env:
          BUILD_FLAGS: ""
      - id: upload-build
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-svc-review-${{ needs.initialize.outputs.target_version }}-${{ matrix.go-os }}-${{ matrix.go-arch }}
          path: dist/*
        env:
          BUILD_FLAGS: ""
    strategy:
      matrix:
        go-arch:
          - amd64
        go-os:
          - linux
        go-version:
          - stable
    needs:
      - initialize
  initialize:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: branch-check
        name: Branch Verification
        run: |2
          echo "ERROR: You can only merge to main from [bugfix/* chore/* feat/* feature/* fix/*]"
          exit 1
        if: '!contains(github.head_ref, ''bugfix/'') && !contains(github.head_ref, ''chore/'') && !contains(github.head_ref, ''feat/'') && !contains(github.head_ref, ''feature/'') && !contains(github.head_ref, ''fix/'')'
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Validate Pull Request Title
        uses: ytanikin/pr-conventional-commits@1.4.1
        with:
          add_scope_label: true
          custom_labels: '{"feat": "release/minor"}'
          task_types: '["feat", "fix", "docs", "test", "ci", "refactor", "perf", "chore", "revert"]'
      - id: release-label
        uses: actions-ecosystem/action-release-label@v1
      - id: get-latest-tag
        name: Get Latest Tag
        run: |2
          LATEST_TAG=$(git tag -l --sort -version:refname --format="%(refname:strip=2)" --merged | head -n 1)
          if [ -z "${LATEST_TAG}" ]; then
          	LATEST_TAG="v0.0.1"
          fi
          echo "Latest known branch tag: ${LATEST_TAG}"
          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
      - id: bump-semver
        name: Compute Target Tag
        uses: cbrgm/semver-bump-action@v1.0.39
        with:
          bump-level: ${{ steps.release-label.outputs.level  || 'patch' }}
          current-version: ${{ steps.get-latest-tag.outputs.tag }}
          prerelease-tag: ""
    outputs:
      current_version: ${{ steps.get-latest-tag.outputs.tag }}
      target_version: ${{ steps.bump-semver.outputs.new_version }}
  merge-authorized:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: merge-authorized
        name: Merge Authorized
        working-directory: .
        run: echo 'Authorized!'
    needs:
      - analyze
      - build
      - initialize
      - test
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: setup-go
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - id: app-token
        name: Authenticate Read-Only App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TWINSCAN_READ_ONLY_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.TWINSCAN_READ_ONLY_APP_PRIVATE_KEY }}
      - id: cross-registry-access
        name: Configure cross registry access
        run: git config --global url."https://x-oauth-basic:$MASTER_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          MASTER_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: install-dep
        name: Install dependencies
        run: go mod download
      - id: go-generate
        name: Run generate
        run: go generate ./...
      - id: go-test
        name: Run Tests
        run: set -o pipefail; go test -json ./... | tee test-out.json
      - id: install-ctrf-reporter
        name: Install CTRF reporter
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
        if: ${{ always() }}
      - id: process-ctrf-results
        name: Process CTRF Test Results
        run: |2
          mkdir ctrf
          cat test-out.json | go-ctrf-json-reporter -output ./ctrf/report.json
        if: ${{ always() }}
        continue-on-error: true
      - id: publish-ctrf-results
        name: Publish CTRF Test Results
        uses: ctrf-io/github-test-reporter@v1
        with:
          failed-report: true
          flaky-report: true
          previous-results-report: true
          pull-request: true
          pull-request-report: true
          report-path: ./ctrf/*.json
          skipped-report: true
          slowest-report: false
          suite-folded-report: false
          suite-list-report: false
          summary-report: true
          test-list-report: false
          title: Test Report
          update-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ always() }}
    strategy:
      matrix:
        go-version:
          - stable
    needs:
      - initialize
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
