name: Push to main [sandbox-svc-review]
run-name: ""
"on":
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: setup-go
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - id: app-token
        name: Authenticate Read-Only App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TWINSCAN_READ_ONLY_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.TWINSCAN_READ_ONLY_APP_PRIVATE_KEY }}
      - id: cross-registry-access
        name: Configure cross registry access
        run: git config --global url."https://x-oauth-basic:$MASTER_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          MASTER_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: install-dep
        name: Install dependencies
        run: go mod download
      - id: go-generate
        name: Run generate
        run: go generate ./...
      - id: go-analysis-config
        name: Configure Static Analysis
        run: |2
          cat <<-EOF > .golangci.yml
          version: "2"
          linters:
            exclusions:
              presets:
                - comments
                - common-false-positives
                - legacy
                - std-error-handling
              paths:
                - third_party$
                - builtin$
                - examples$
          formatters:
            exclusions:
              paths:
                - third_party$
                - builtin$
                - examples$
          EOF
      - id: go-analysis
        name: Static Analysis
        uses: golangci/golangci-lint-action@v8
        with:
          args: --verbose --timeout=15m
          version: latest
    strategy:
      matrix:
        go-version:
          - stable
    needs:
      - initialize
    permissions:
      checks: write
      contents: read
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: setup-go
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - id: app-token
        name: Authenticate Read-Only App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TWINSCAN_READ_ONLY_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.TWINSCAN_READ_ONLY_APP_PRIVATE_KEY }}
      - id: cross-registry-access
        name: Configure cross registry access
        run: git config --global url."https://x-oauth-basic:$MASTER_TOKEN@github.com/".insteadOf "https://github.com/"
        env:
          MASTER_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: install-dep
        name: Install dependencies
        run: go mod download
      - id: go-generate
        name: Run generate
        run: go generate ./...
      - id: go-build
        name: Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.go-os }} GOARCH=${{ matrix.go-arch }} go build  -v -o ./dist/sandbox-svc-review cmd/main.go
      - id: upload-build
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-svc-review-${{ needs.initialize.outputs.target_version }}-${{ matrix.go-os }}-${{ matrix.go-arch }}
          path: dist/*
    strategy:
      matrix:
        go-arch:
          - amd64
        go-os:
          - linux
        go-version:
          - stable
    needs:
      - initialize
  containerize-sandbox-svc-review-build:
    runs-on:
      - ubuntu-latest
    name: Containerize sandbox-svc-review
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: download-artifacts
        name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/
          pattern: sandbox-svc-review-${{ needs.initialize.outputs.target_version }}-${{ matrix.go-os }}-${{ matrix.go-arch }}
      - id: gcloud-setup
        name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - id: gcp-auth-access-token
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.TWINSCAN_INFRASTREAM_PORTAL_PROJECT_ID }}
          service_account: ${{ secrets.TWINSCAN_GOOGLE_ACTIONS_SERVICE_ACCOUNT }}
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
      - id: docker-setup
        name: Setup Docker Actions
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |-
            {
                          "debug": true,
                          "features": {
                            "containerd-snapshotter": true
                          }
                        }
      - id: docker-login-docker-private
        name: Authenticate to Docker docker-private Registry
        uses: docker/login-action@v3
        with:
          password: ${{ steps.gcp-auth-access-token.outputs.access_token }}
          registry: africa-south1-docker.pkg.dev/infrastream-core-executor-0f7f/docker-private
          username: oauth2accesstoken
      - id: app-token
        name: Authenticate Read-Only App
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TWINSCAN_READ_ONLY_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.TWINSCAN_READ_ONLY_APP_PRIVATE_KEY }}
      - id: docker-prepare
        name: Prepare Environment
        run: |2
          platform=${{ matrix.go-os }}/${{ matrix.go-arch }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - id: docker-meta
        name: Resolve image metadata
        uses: docker/metadata-action@v5
        with:
          images: africa-south1-docker.pkg.dev/infrastream-core-executor-0f7f/docker-private/sandbox-svc-review
      - id: setup-qemu
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - id: setup-buildx
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - id: docker-build
        name: Build Docker
        uses: docker/build-push-action@v6
        with:
          build-args: |-
            RELEASE_TYPE=latest
            RELEASE_VERSION=${{ needs.initialize.outputs.target_version }}
          context: .
          file: Dockerfile.infrastream
          labels: ${{ steps.docker-meta.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          platforms: ${{ matrix.go-os }}/${{ matrix.go-arch }}
          secrets: github_token=${{ steps.app-token.outputs.token }}
          tags: africa-south1-docker.pkg.dev/infrastream-core-executor-0f7f/docker-private/sandbox-svc-review
      - id: docker-digest
        name: Export Digest
        run: |2
          mkdir -p ${{ runner.temp }}/sandbox-svc-review-digests
          digest="${{ steps.docker-build.outputs.digest }}"
          touch "${{ runner.temp }}/sandbox-svc-review-digests/${digest#sha256:}"
      - id: docker-upload-digest
        name: Upload Digest
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: sandbox-svc-review-digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/sandbox-svc-review-digests/*
          retention-days: 1
    strategy:
      matrix:
        go-arch:
          - amd64
        go-os:
          - linux
        go-version:
          - stable
    needs:
      - initialize
      - tag
    permissions:
      contents: read
      id-token: write
  containerize-sandbox-svc-review-publish:
    runs-on:
      - ubuntu-latest
    name: Publish Containers
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: gcloud-setup
        name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - id: gcp-auth-access-token
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.TWINSCAN_INFRASTREAM_PORTAL_PROJECT_ID }}
          service_account: ${{ secrets.TWINSCAN_GOOGLE_ACTIONS_SERVICE_ACCOUNT }}
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
      - id: docker-setup
        name: Setup Docker Actions
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |-
            {
                          "debug": true,
                          "features": {
                            "containerd-snapshotter": true
                          }
                        }
      - id: docker-login-docker-private
        name: Authenticate to Docker docker-private Registry
        uses: docker/login-action@v3
        with:
          password: ${{ steps.gcp-auth-access-token.outputs.access_token }}
          registry: africa-south1-docker.pkg.dev/infrastream-core-executor-0f7f/docker-private
          username: oauth2accesstoken
      - id: download-digests
        name: Download image digests
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ${{ runner.temp }}/sandbox-svc-review-digests
          pattern: sandbox-svc-review-digests-*
      - id: docker-meta
        name: Resolve image metadata
        uses: docker/metadata-action@v5
        with:
          images: africa-south1-docker.pkg.dev/infrastream-core-executor-0f7f/docker-private/sandbox-svc-review
          tags: |-
            type=semver,pattern={{raw}},value=${{ needs.initialize.outputs.target_version }}
            type=sha
            type=raw,value=latest
      - id: setup-buildx
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - id: docker-image-create
        name: Create Docker Image
        working-directory: ${{ runner.temp }}/sandbox-svc-review-digests
        run: |2
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          	$(printf 'africa-south1-docker.pkg.dev/infrastream-core-executor-0f7f/docker-private/sandbox-svc-review@sha256:%s ' *)
      - id: notify-deployer
        name: Notify InfraStream Deployer
        working-directory: .
        run: gcloud pubsub topics publish projects/${{ secrets.TWINSCAN_INFRASTREAM_PORTAL_PROJECT_ID }}/topics/deployment-notifications --message='{"branchName":"${{ github.ref }}","buildDefinition":"sandbox-svc-review","container":"sandbox-svc-review","githubConnection":"default","repository":"sandbox-svc-review","version":"${{ needs.initialize.outputs.target_version }}"}'
    needs:
      - containerize-sandbox-svc-review-build
      - initialize
      - tag
    permissions:
      contents: read
      id-token: write
  initialize:
    runs-on:
      - ubuntu-latest
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Validate Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: get-merged-pull-request
        name: Retrieve Pull Request Data
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: release-label
        name: Compute Release Label
        uses: actions-ecosystem/action-release-label@v1
        with:
          labels: ${{ steps.get-merged-pull-request.outputs.labels }}
        if: ${{ steps.get-merged-pull-request.outputs.title != null }}
      - id: get-latest-tag
        name: Get Latest Tag
        run: |2
          LATEST_TAG=$(git tag -l --sort -version:refname --format="%(refname:strip=2)" --merged | head -n 1)
          if [ -z "${LATEST_TAG}" ]; then
          	LATEST_TAG="v0.0.1"
          fi
          echo "Latest known branch tag: ${LATEST_TAG}"
          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
      - id: bump-semver
        name: Compute Target Tag
        uses: cbrgm/semver-bump-action@v1.0.39
        with:
          bump-level: ${{ steps.release-label.outputs.level  || 'patch' }}
          current-version: ${{ steps.get-latest-tag.outputs.tag }}
          prerelease-tag: ""
    outputs:
      current_version: ${{ steps.get-latest-tag.outputs.tag }}
      target_version: ${{ steps.bump-semver.outputs.new_version }}
  tag:
    runs-on:
      - ubuntu-latest
    name: Tag commit ${{ needs.initialize.outputs.target_version }}
    steps:
      - id: harden-runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: git-cliff
        name: Build Changelog
        uses: orhun/git-cliff-action@v4
        with:
          args: -vv --latest --unreleased --tag ${{ needs.initialize.outputs.target_version }} --strip header
          config: cliff.toml
        env:
          GITHUB_REPO: ${{ github.repository }}
          OUTPUT: .changelog.md
        if: ${{ hashFiles('CHANGELOG.md') == '' }}
      - id: changelog-extract
        name: Extract Changelog
        working-directory: .
        run: |2
          tag="${{ needs.initialize.outputs.target_version }}"
          version="${tag#v}"
          awk -v ver="$version" '
           /^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next} } p && NF
          ' CHANGELOG.md > .changelog.md
        if: ${{ hashFiles('CHANGELOG.md') != '' }}
      - id: git-tag
        name: Tag commit ${{ needs.initialize.outputs.target_version }}
        working-directory: .
        run: "\ntag=${{ needs.initialize.outputs.target_version }}\ngit config user.name 'github-actions[bot]'\ngit config user.email '41898282+github-actions[bot]@users.noreply.github.com'\ngit tag -a -F .changelog.md \"${tag}\" \ngit push origin \"${tag}\""
    needs:
      - analyze
      - build
      - initialize
    permissions:
      actions: write
      contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
